name = "TraceMakie"
uuid = "70852e3a-d594-4041-8350-783a02753e02"
version = "1.0.0-DEV"
authors = ["Simon Danisch"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Hikari = "afc56b53-c9a9-482a-a956-d1d800e05558"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Raycore = "afc56b53-c9a9-482a-a956-d1d800e05559"

[sources]
Hikari = {path = "../Hikari"}
Raycore = {path = "../Raycore"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
